## Data Preparation

In [77]:
import uproot
import numpy as np

In [78]:
# inspection
run2 = uproot.open("/home/vulcan/Documents/coding/datasets/ODEO_FEB2025_v0_2J2LMET30_data16_periodL.2J2LMET30.root")["analysis;1"]

types = run2.typenames()
type_lookup = list(set(types.values()))

In [79]:
for a, b in types.items():
    if b in type_lookup:
        print(run2[a].array(library="np")[:5], b, "\n\n")
        type_lookup.remove(b)

[1. 1. 1. 1. 1.] double 


['data16' 'data16' 'data16' 'data16' 'data16'] std::string 


[array([ True,  True]) array([ True,  True]) array([False,  True,  True])
 array([ True,  True]) array([ True,  True])] RVec<bool> 


[2 2 2 2 2] uint64_t 


[1. 1. 0. 0. 1.] float 


[311287 311287 311287 311287 311287] uint32_t 


[False False False False False] bool 


[2 2 3 2 2] int32_t 


[array([35.86335 , 25.275734], dtype=float32)
 array([55.490837, 20.517515], dtype=float32)
 array([140.3014  ,  49.207405,  20.676874], dtype=float32)
 array([25.637583, 21.195396], dtype=float32)
 array([28.12369 , 29.869343], dtype=float32)] RVec<float> 


[array([1, 1], dtype=int32) array([1, 1], dtype=int32)
 array([1, 5, 1], dtype=int32) array([1, 1], dtype=int32)
 array([1, 1], dtype=int32)] RVec<int32_t> 




In [80]:
jpt = run2["jet_pt"].array(library="np")
[jpt[a].size for a in range(len(jpt))]

[2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 2,
 3,
 2,
 3,
 2,
 2,
 4,
 2,
 3,
 2,
 2,
 3,
 3,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 3,
 3,
 2,
 4,
 2,
 2,
 2,
 2,
 5,
 4,
 3,
 2,
 3,
 5,
 2,
 3,
 2,
 3,
 3,
 4,
 2,
 2,
 2,
 2,
 4,
 2,
 3,
 2,
 3,
 2,
 3,
 2,
 4,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 3,
 3,
 3,
 2,
 2,
 4,
 3,
 4,
 4,
 2,
 4,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 3,
 2,
 4,
 3,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 6,
 3,
 2,
 2,
 3,
 2,
 3,
 3,
 2,
 3,
 2,
 2,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 4,
 2,
 2,
 2,
 4,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 2,
 4,
 5,
 3,
 3,
 4,
 2,
 4,
 2,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 3,
 3,
 2,
 2,
 4,
 2,
 4,
 2,
 2,
 3,
 2,
 2,
 3,
 4,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 2,
 4,
 3,
 5,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 3,
 2,
 2,
 4,
